"""empty message

Revision ID: 9275e4ce4382
Revises: f57417c1599d
Create Date: 2023-05-07 11:00:27.195644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9275e4ce4382'
down_revision = 'f57417c1599d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_login')
        batch_op.drop_column('login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_users_login', ['login'], unique=False)

    # ### end Alembic commands ###
